Repository operate-first/curator, pull requests merged in 2021-08, with the labels that each got.

#88 Fix an indentation error in earlier PR
  Documentation/credentials/credentials.env
  scripts/postgres_interface.py
  scripts/unzip_backup.py
Labels: size/S, lgtm, approved

#91 Database and small bug fixes
  cronjob.yaml
  scripts/reports/generate_report.psql
  scripts/unzip_backup.py
Labels: size/M, lgtm, approved

#92 Generate report grouped by namespaces
  scripts/reports/generate_report.psql
Labels: lgtm, approved

#80 Curator test cases cont.
  .gitignore
  scripts/unzip_backup.py
  testing/config_test.env
  testing/credentials_test.env
  testing/curator-test.py
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.0.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.1.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.2.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.3.csv
  testing/goldendata/20210616T125440-cost-mgmt/manifest.json
  testing/kustomization.yml
  testing/scripts/test-backup.sh
  testing/scripts/test-database.sh
  testing/testS3.yaml
  testing/testdata/20210616T125440-cost-mgmt.tar.gz
  verify_connection.sh
Labels: size/XXL, lgtm, approved
