Repository operate-first/curator, pull requests merged in 2021-06, with the labels that each got.

#30 backup-to-bucket
  Documentation/config/config.env
  Documentation/credentials/credentials_example.env
  README.md
  cronjob.yaml
  kustomization.yaml
  scripts/run-backup.sh
Labels: approved, lgtm, size/L

#36 Updated README.md for v0.2 release
  README.md
Labels: approved, lgtm, size/S

#39 kokumetrics config added
  Documentation/config/config.env
  Documentation/config/kokumetric-config.yaml
  Documentation/config/kokumetris-cfg.yaml
  cronjob.yaml
Labels: approved, lgtm, size/L

#49 Issue48
  Documentation/PRD.md
  README.md
  console/.dockerignore
  console/.github/PULL_REQUEST_TEMPLATE/devconsole_pr.md
  console/.gitignore
  console/README.md
Labels: approved, lgtm, v0.3
