Repository operate-first/curator, pull requests merged in 2021-11, with the labels that each got.

#154 Fix Superset compatibility issue in db
  database/scripts/psql_queries/create_table.psql
  database/scripts/psql_queries/generate_report.psql
  scripts/unzip_backup.py
Labels: size/M, lgtm, approved

#132 Upgrade db to v13, add table partitioning support
  Documentation/config/postgresql/dockerfile/Dockerfile
  Documentation/config/postgresql/dockerfile/fix-permissions
  Documentation/config/postgresql/dockerfile/initdb.sh
  Documentation/config/postgresql/postgres-database-cfg.yaml
  database/scripts/psql_queries/create_table.psql
Labels: lgtm, approved, size/L

#160 Update table partition parameters
  database/scripts/psql_queries/create_table.psql
  scripts/unzip_backup.py
Labels: size/S, lgtm, approved

#162 Removed un-necessary try catch to raise exception
  scripts/postgres_interface.py
  scripts/unzip_backup.py
Labels: lgtm, approved, size/L
