Repository operate-first/curator, pull requests merged in 2021-07, with the labels that each got.

#51 Unzip files
  cronjob.yaml
  kustomization.yaml
Labels: approved, lgtm, size/S

#54 Readme updated for v0.3
  Documentation/config/config.env
  README.md
  cronjob.yaml
  scripts/unzip_backup.py
Labels: approved, lgtm, size/S

#55 V0.3
  Documentation/config/config.env
  Documentation/config/kokumetric-config.yaml
  Documentation/config/kokumetris-cfg.yaml
  README.md
  cronjob.yaml
  kustomization.yaml
  scripts/unzip_backup.py
Labels: approved, lgtm, size/L

#59 Create reports generation
  Documentation/Sample Weekly Report.csv
  scripts/reports/day_report_cronjob.yaml
  scripts/reports/generate_report.psql
  scripts/reports/month_report_cronjob.yaml
  scripts/reports/week_report_cronjob.yaml
  scripts/unzip_backup.py
Labels: approved, size/L

#58 Code to push unzipped files to database
  Documentation/config/config.env
  README.md
  scripts/unzip_backup.py
Labels: approved, size/L

#61 Add report generation documentation to README
  README.md
Labels: approved, lgtm, size/S

#62 V0.4
  Documentation/Sample Weekly Report.csv
  Documentation/config/config.env
  README.md
  scripts/reports/day_report_cronjob.yaml
  scripts/reports/generate_report.psql
  scripts/reports/month_report_cronjob.yaml
  scripts/reports/week_report_cronjob.yaml
  scripts/unzip_backup.py
Labels: approved, lgtm, size/L
