Repository operate-first/curator, pull requests merged in 2021-09, with the labels that each got.

#94 Opt out S3 in test case; use 13 as postgres image version number
  README.md
  scripts/reports/day_report_cronjob.yaml
  scripts/reports/month_report_cronjob.yaml
  scripts/reports/week_report_cronjob.yaml
  testing/curator-test.py
Labels: size/M, lgtm, approved

#95 V0.4.1
  .gitignore
  Documentation/config/config.env
  Documentation/credentials/credentials.env
  README.md
  cronjob.yaml
  install.sh
  kustomization.yaml
  scripts/postgres_interface.py
  scripts/reports/day_report_cronjob.yaml
  scripts/reports/generate_report.psql
  scripts/reports/month_report_cronjob.yaml
  scripts/reports/week_report_cronjob.yaml
  scripts/unzip_backup.py
  testing/config_test.env
  testing/credentials_test.env
  testing/curator-test.py
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.0.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.1.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.2.csv
  testing/goldendata/20210616T125440-cost-mgmt/a5186c28-6b78-44eb-af59-d739aeaca676_openshift_usage_report.3.csv
  testing/goldendata/20210616T125440-cost-mgmt/manifest.json
  testing/kustomization.yml
  testing/scripts/test-backup.sh
  testing/scripts/test-database.sh
  testing/testS3.yaml
  testing/testdata/20210616T125440-cost-mgmt.tar.gz
  verify_connection.sh
Labels: lgtm, approved

#98 fix report timing
  scripts/reports/generate_report.psql
Labels: size/S, lgtm, approved

#100 fix report timing
  scripts/reports/generate_report.psql
Labels: size/M, lgtm, approved

#97 Database history table updated
  scripts/postgres_interface.py
  scripts/unzip_backup.py
Labels: size/M, lgtm, approved

#101 Single script installation
  kustomization.yaml
  scripts/postgres_interface.py
  scripts/reports/create_table.psql
  scripts/unzip_backup.py
Labels: lgtm, approved, size/L

#103 V1.1
  kustomization.yaml
  scripts/postgres_interface.py
  scripts/reports/create_table.psql
  scripts/reports/generate_report.psql
  scripts/unzip_backup.py
Labels: lgtm, approved, size/L
